### ISSUE TITLE
TypeError: chunk.sortModules is not a function

### ISSUE THREAD

**Issue by trsh** [webpack-contrib/extract-text-webpack-plugin#574]
v3.0.0

TypeError: chunk.sortModules is not a function TypeError: chunk.sortModules is not a function
    at C:\Projects\flowww-web\node_modules\extract-text-webpack-plugin\dist\index.js:188:19
    at C:\Projects\flowww-web\node_modules\async\dist\async.js:3083:16
    at eachOfArrayLike (C:\Projects\flowww-web\node_modules\async\dist\async.js:1003:9)
    at eachOf (C:\Projects\flowww-web\node_modules\async\dist\async.js:1051:5)
    at Object.eachLimit (C:\Projects\flowww-web\node_modules\async\dist\async.js:3145:5)
    at Compilation.<anonymous> (C:\Projects\flowww-web\node_modules\extract-text-webpack-plugin\dist\index.js:184:27)
    at Compilation.applyPluginsAsyncSeries (C:\Projects\flowww-web\node_modules\tapable\lib\Tapable.js:142:13)
    at Compilation.seal (C:\Projects\flowww-web\node_modules\webpack\lib\Compilation.js:580:8)
    at C:\Projects\flowww-web\node_modules\webpack\lib\Compiler.js:510:16
    at C:\Projects\flowww-web\node_modules\tapable\lib\Tapable.js:225:11
    at _addModuleChain (C:\Projects\flowww-web\node_modules\webpack\lib\Compilation.js:482:11)
    at processModuleDependencies.err (C:\Projects\flowww-web\node_modules\webpack\lib\Compilation.js:453:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by trsh** [comment]
Solved with updating webpack to 3.3.0.

**Comment by BkunS** [comment]
Still have the problem with Webpack^3.4.1 with extract-text-webpack-plugin^3.0.0.
webpack.config.js:
...
module: {
    rules: [
    {
        test: /\.css$/,
        include: path.join(__dirname, 'src', 'css'),
        use: ExtractTextPlugin.extract({ fallback: 'style-loader', use: 'css-loader' }),
      }
     ],
},
plugins: [
    new ExtractTextPlugin('bundle.css'),
]
...

**Comment by chenwenxian** [comment]
Very good method!
