### ISSUE TITLE
common + vendor chunks and ExtractTextPlugin problem

### ISSUE THREAD

**Issue by deepsweet** [webpack-contrib/extract-text-webpack-plugin#58]
hi.

I have a setup:

``` js
entry: {
    vendor: [ 'vendor-js', 'vendor-styles.css' ],
    a: './a.js',
    b: './b.js'
},
...
plugins: [
    new webpack.optimize.CommonsChunkPlugin({
        name: 'common',
        filename: 'build/js/[name].js',
        chunks: [ 'a', 'b' ]
    }),
    new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor',
        filename: 'build/js/[name].js'
    }),
    new ExtractTextPlugin('build/css/[name].css', {
        allChunks: true
    })
]
```

JS files are generated fine, `build/js/vendor.js` contains "vendor-js", `build/js/common.js` contains shared between `a.js` and `b.js` modules, and so on:

```
build/js/
├── a.js
├── b.js
├── common.js
└── vendor.js
```

but CSS:

```
build/css/
└── vendor.css
```

`build/css/vendor.css` contains both `vendor-styles.css` and styles from `build/js/common.js` (styles required both in `a.js` and `b.js`). and there is no `build/css/common.css`.

is setup looks ok and this is a bug?

**Comment by sokra** [comment]
Setup looks ok. Maybe it helps to switch the order of ETP and CommonsChunkPlugin. Elsewise it's a bug.

**Comment by deepsweet** [comment]
the issue was solved when I directly added some stuff to common chunk in `entry` section. so it looks like plugin just can't catch "dynamic" chunks created by CommonsChunkPlugin. feel free to close this issue, but imo it's more a bug than a feature :)

**Comment by jonashartwig** [comment]
Unfortunately this issue persists. I have a similar configuration:
```js
const entryPath = path.resolve(__dirname, "src", "modules"),
    publicPath = path.resolve(__dirname, "dist"),
    pathToAppJs = path.resolve(__dirname, "..", "src", "main", "webapp", "js", "react", "app-dist"),
    pathToAppCss = path.resolve(__dirname, "..", "src", "main", "webapp", "css", "react", "app-dist"),
    isProduction = "production" === process.env.NODE_ENV,
    esLintConfig = path.resolve(__dirname, "eslintrc.config"),
    entryPoints = {
        vendor: ["babel-polyfill", "react", "react-dom", "immutable", "moment", "moment-timezone", "mousetrap", "react-redux", "redux", "redux-thunk"],
        pivot: entryPath + "/pivot.js",
        a: entryPath + "/a.js",
        b: entryPath + "/b.js",
        c: entryPath + "/c.js",
        d: entyPath + "/d.js",
        e: entryPath + "e.js",
        f: entryPath + "f.js",
        g: entryPath + "/g.js",
        h: entryPath + "/h.js"
    }, plugins = [
        new CommonsChunkPlugin("vendor", "vendor.bundle.js"),
        new CommonsChunkPlugin({
            name: "commons",
            filename: "commons.bundle.js",
            minChunks: 2,
            chunks: Object.keys(entryPoints).filter(key => key !== "vendor")
        }),
        new ExtractTextPlugin("[name].bundle.css", {
            //allChunks: true
        })
    ];
```

It puts some css code into vendor.bundle.css which is missing in commons.bundle.css

**Comment by jonashartwig** [comment]
if i revert the common chunk plugin order it seems to work:

```js
plugins = [
        new CommonsChunkPlugin("vendor", "vendor.bundle.js"),
        new CommonsChunkPlugin({
            name: "commons",
            filename: "commons.bundle.js",
            minChunks: 2,
            chunks: Object.keys(entryPoints).filter(key => key !== "vendor")
        }),
        new ExtractTextPlugin("[name].bundle.css", {
            //allChunks: true
        })
    ];
```

**Comment by lucaseverett** [comment]
This is happening for me as well. I can't find a way to create a commons.css file -- only commons.js. I've tried a few tricks, such as adding a commons entry point and changing order of plugins, but nothing works.

**Comment by uptownhr** [comment]
bump

**Comment by marco-a** [comment]
Having the same issue here

**Comment by quantix-studio** [comment]
same issue

**Comment by thiagof** [comment]
Persists?

Version: webpack 1.14.0

**Comment by thiagof** [comment]
The issue seems on understanding the tool (or documenting).

I was expecting that the Text Extracted would be match and separated in common chunks. **But no**.
What *seems* to be matched as common are file names.

So if you import in sass code, it will not match

```scss
// do not go to commons
@import 'bootstrap/scss/bootstrap';
```

What works are importing in javascript the required files, even if they are scss.

```js
// matches on common chunk
require('bootstrap/scss/bootstrap');
```

This is correct to assert?

**Comment by Invis1ble** [comment]
@deepsweet

> the issue was solved when I directly added some stuff to common chunk in entry section. so it looks like plugin just can't catch "dynamic" chunks created by CommonsChunkPlugin.

Can you share your modification please? I'm new in webpack but seems I have the same issue and I can't get how to workaround it :(

Here is my config:

```js
module.exports = {
    context: srcPath,
    entry: {
        foo: './css/pages/foo.css',
        bar: './css/pages/bar.css'
    },
    output: {
        path: distPath,
        publicPath: '/assets/',
        filename: '[name].js'
    },
    module: {
        rules: [{
            test: /\.css$/,
            use: ExtractTextPlugin.extract([
                'css-loader'
            ])
        }]
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: 'common',
            minChunks: 2
        }),
        new ExtractTextPlugin({
            filename: 'css/[name].[contenthash:base64:5].css',
            allChunks: true
        })
    ]
};
```

After generating I have no `common.css`, but there are `common.js`, `foo.js`, `bar.js`, `foo.css` and `bar.css`.

**Comment by deepsweet** [comment]
@Invis1ble sorry I don't remember any details of my workaround, it was almost 2 years ago.

**Comment by gabn88** [comment]
This bug/feature bit me as well. Using extractText in combination with CommonsChunk and sass-loader is not working. I guess extractText is the devil here, but I'm not sure.

I'd like to keep the css file small, which was one of the main reasons of migrating to webpack. However, if you 'ES6 import' the sass file inside the entries.js, and then import other sass files with an @import statement (using sass-loader's import system), the css is never put into a common file, although the css from different entries goes into different css files (but again, not in the common-css).

By the way, I'm using webpack 2.2.1 and     "sass-loader": "^6.0.2" and     "extract-text-webpack-plugin": "^2.0.0".

**Comment by prograhammer** [comment]
It seems ExtractTextPlugin can't catch the chunks created implicitly with the `minChunks` function of CommonChunksPlugin. Anyone else experiencing this and know if there is a work-around?

**Comment by Vivi-wu** [comment]
Expect the same result as @gabn88, but not success yet.

webpack@2.6.1, 
sass-loader@6.0.5, 
extract-text-webpack-plugin@2.1.0

**Comment by Giovanni-Mattucci** [comment]
@Vivi-wu are you making sure that you require in your sass within a JS file somewhere?

**Comment by evilebottnawi** [comment]
Somebody can create minimum reproducible test repo? This will speed up to found a solution.

**Comment by bjunc** [comment]
There might be different reasons for each person's setup failing to create a `common.css`.  However, it at least seems in-part to do with `require` vs `@import`.  Albeit dated, this [webpack example](https://github.com/webpack/webpack/tree/master/examples/multiple-entry-points-commons-chunk-css-bundle) (multiple entries, common css) seems to illustrate this, and might serve as a good test repo.

**Comment by Vivi-wu** [comment]
Just put my experiment project on Github, here is the link [https://github.com/Vivi-wu/multipage-webpack](link)

Since I‘m new to webpack, I borrow the webpack config/structure from [vue-cli](https://github.com/vuejs-templates/webpack)

The project does not work as I expect, but I don't have much time to dig into it at present. 

FYI @Giovanni-Mattucci @evilebottnawi

**Comment by RohitRox** [comment]
Still seeing issues with extracting `@import` in `scss` files to common css bundle. Is there a workaround?

**Comment by JerryCBH** [comment]
Having the same issue here - no common css extracted. I have 3 entries:

```
plugins: [
    new webpack.DefinePlugin({
      'process.env': env
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      },
      sourceMap: true
    }),
    new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css')
    }),
    new OptimizeCSSPlugin({
      cssProcessorOptions: {
        safe: true
      }
    }),
    new HtmlWebpackPlugin({
      filename: process.env.NODE_ENV === 'testing'
        ? 'index.html'
        : config.build.index,
      template: 'index.html',
      inject: false,
      hash: true,
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: false,
        minifyJS: true
      },
      chunksSortMode: appChunkOrder
    }),
    new HtmlWebpackPlugin({
      filename: process.env.NODE_ENV === 'testing'
        ? 'src/Login/login.html'
        : config.build.login,
      template: 'src/Login/login.html',
      inject: false,
      hash: true,
      minify: false,
      chunksSortMode: loginChunkOrder
    }),
    new HtmlWebpackPlugin({
      filename: process.env.NODE_ENV === 'testing'
        ? 'src/Register/register.html'
        : config.build.register,
      template: 'src/Register/register.html',
      inject: false,
      hash: true,
      minify: false,
      chunksSortMode: registerChunkOrder
    }),    
    new webpack.optimize.CommonsChunkPlugin({
      name: 'app.vendor',
      chunks: ['app'],
      minChunks: isVendor,
    }),    
    new webpack.optimize.CommonsChunkPlugin({
      name: 'login.vendor',
      chunks: ['login'],
      minChunks: isVendor,
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'register.vendor',
      chunks: ['register'],
      minChunks: isVendor,
    }),    
    new webpack.optimize.CommonsChunkPlugin({
      name: 'common',
      chunks: ['app.vendor', 'login.vendor', 'register.vendor', 'app', 'login', 'register'],
      minChunks: (module, count) => count >= 2 && isVendor(module),
    }),
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.build.assetsSubDirectory,
        ignore: ['.*']
      }
```

**Comment by Robula** [comment]
Same issue here. I get a common.css if I import CSS via JS but not if using CSS3 imports. This is an issue because I must use CSS3 imports in order for postcss-next to work correctly.

**Comment by Robula** [comment]
Is this just a case of `CommonsChunkPlugin` only supporting JS files and therefore calling `import './styles.css'` in a JS file works and imported CSS `@import`s don't?

**Comment by JerryCBH** [comment]
@Robula 
What happen if you import third party libraries and packages and you won't have control over how CSS are imported by those packages?

**Comment by valkon** [comment]
I found a graceful workaround for a similar problem. Just add a `importLoaders=false` to сss-loader options.
Here is example config:

```
let config = {
    context: SRC,
    entry: {
        'bundle1': './test1.css',
        'bundle2': './test2.css',
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                loader: ExtractPlugin.extract(['css-loader?importLoaders=false'])
            }
        ]
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: 'common',
            chunks: ['bundle1', 'bundle2']
        }),
        new ExtractPlugin({
            filename: '[name].css?hash=[contenthash]',
        }),
    ]
};
```
